language: bash
before_install:
- sudo apt-get update
- sudo apt-get install -y --no-install-recommends texlive-full latexmk
install: true
script:
- make a4
deploy:
  local-dir: dest
  provider: pages
  target-branch: gh-pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"

env:
  global:
    secure: WPNFDqHnXv0L8Qz73uul8q57fHxhBleJ+lfF4l2XFlWGWKbKmnbl0MXa5Q6vHIJxdPlaDt5jTv4VgbRdimEBpsoYScvmOClyA0flVVyfctN9MwjFTyCMSjq59yU/lKfVBWfuueZfQl1DRJQUGlmdjFPbEUc4Cy4ORE6eapAeR58/VUwgppf70hIkF6tKfMlz3zF0cDMgIG1t4sNg1Q92A41hiGhnx7GdgTa06iSYbLLuLA6Z6rWy9LupVNlxqbYW7izrC2l5XANOZge5886RFA6LYUeT30aJrLZJ+gzHfGZQgi7AWeDC4Bt1UJ9yzkCBITrNAjlx6rus1BcrVueTmcspcUww8ggDU3cbtzIuiBxbsoWIL3uWSMfH7kneT7UasQNrgR71wi3ETbZf9peRCORidtXnJQ9ogZ8Y9qeP+9GIq4bgDz+TFBkz8aiOxbqgKuWHemCC1sUwSWZcm3Id10l2kcmCg1CB/r3f90nifkfFA3T4lZrqj+QtjH+/RU8gWRdcuWDaEllvyJE+axjEv+dIfYwgzpfxgUpbXoDHuxi8MoKJGgnEkeaivAf718p4ds0bfBnL3RZ8fl/Ztsf2soGKvIPSXAxOmXVgoFh5wk7aXBoa/pMJNH5TQTM6GfKzutIJ+v4MuFBzdDtwP54rTH99YBlem8apPfDNZjgXVVk=
