
language: bash 
before_install:
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends texlive-full latexmk

install: true

script:
- make a4

deploy:
  local-dir: dest
  provider: pages
  target-branch: gh-pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN


env:
  global:
    secure: ju1UaOgIcTSOeKCogIQnejh7K8Qiqtkg2meX8xXw4MP5GZVum6prlEuJTmK/hS7n/y5AjffWVPGctCo8aIdp8nmrZKSwl6LAbQSZ3El0GfO+TY5rqjq4atT/S1AfKN2w9vfkvJs9EZYmx1mFNxqAwt4XO3ulxFECjWhU/6gor0IC6aF4SapjlWVcw/tcszF6Kn+pNWeI6tLHSk66yvJJqeJF16ykNEjw+0T1z2MCOBWmu5uk0iI776TnDM9fh1DJBDb/8yzup4jxIQWerSSk48x0zXtF1tC3X3hbFLTx7lqnz/zmFCBSOzwXCX0y1bH1cu7na0i4UsN/2xd3wYpRam1j08YVuSjdc1i4u9YX9DnAEk5LHBNI/OnUDXU3f+425W0lShOR+5XVH3xLu+sTH5cfINw24NIcGtcrLNNWUHMdZK6FQCUZMLiEVfXUv7cbkvDN/qz1AFTA6rW59iosuJ/O0YoCxOYjcpmq/oUayCuQO8n4D/xPgyj7/hR/nbN2zFic0f5EiPVxUHIUXqy9Ne58znPM+1tSlP+Se89H9EYTDXy+JrNaHkwEHN+rbFFfRQreg9JJRViNkvQrUGYEog68co4Q8AdYZCXkW9BeKdrgnHeVp1EZtFam21BaOCOwFk4qCgN5o5QyGy5skGbtkP9nOycnjlagyiiHX3OaY/c=
